// Arithmetic Operators
// let a = 8;
// let b = 4;

// console.log("a = ", a, "& b = ", b);
// console.log("a + b = ", a + b);
// console.log("a - b = ", a - b);
// console.log("a * b = ", a * b);
// console.log("a / b = ", a / b);
// console.log("a % b = ", a % b);
// console.log("a ** b = ", a ** b);

// Urinary Operators
// console.log("a = ", a, "& b = ", b);
// a++;
// console.log("a =", a);

// Assignment Operators
// a **= 4;
// console.log("a = ", a);

// Comparison Operators
// console.log("5 == 2", a == b);


//Logical Operators

// let cond_1 = a > b
// let cond_2 = a === 6;
// console.log("cond_1 && cond_2 = ", cond_1 && cond_2)

// let mode = "dark";
// let color;

// if (mode === "dark") {
//     color = "black";
// } else if (mode === "blue") {
//     color = "blue";
// } else if (mode === "pink") {
//     color = "pink";
// } else {
//     color = "white";
// }

// console.log(color);

// if (mode === "dark") console.log(mode);

// let age = 16;

// let result = age >= 18 ? "adult" : "not adult";
// console.log(result);

let name = prompt("Salve!");
console.log(name);








